CREATE DATABASE DW_AIRLINE
GO
USE DW_AIRLINE


-- DIM THOIGIAN
CREATE TABLE DIM_THOIGIAN (
    matg INT PRIMARY KEY NOT NULL,
    ngay INT NOT NULL,
    tuan INT NOT NULL,
    thang INT NOT NULL,
    quy INT NOT NULL,
    nam INT NOT NULL
);


-- DIM KENHBANVE 
CREATE TABLE DIM_KENHBANVE (
    makenh INT PRIMARY KEY NOT NULL,
    tenkenh NVARCHAR(100) NOT NULL,
    mahangve NVARCHAR(50) NOT NULL,
    tenhangve NVARCHAR(50) NOT NULL
);


-- DIM TACVU
CREATE TABLE DIM_TACVU (
    matacvu INT PRIMARY KEY NOT NULL,
    loaitacvu NVARCHAR(100) NOT NULL,
    tentacvu NVARCHAR(100) NOT NULL
);


-- DIM PHIHANHDOAN
CREATE TABLE DIM_PHIHANHDOAN (
    manv INT PRIMARY KEY NOT NULL,
    hoten NVARCHAR(100) NOT NULL,
    gioitinh NVARCHAR(10) NOT NULL,
    chucvu NVARCHAR(50) NOT NULL,
    ngayvaolam DATE NOT NULL,
    diachithuongtru NVARCHAR(255) NOT NULL,
    ngaysinh DATE NOT NULL,
    sdt NVARCHAR(20) NOT NULL
);


-- DIM KHACHHANG
CREATE TABLE DIM_KHACHHANG (
    makh INT PRIMARY KEY NOT NULL,
    hoten NVARCHAR(100) NOT NULL,
    gioitinh NVARCHAR(10) NOT NULL,
    quoctich NVARCHAR(50) NOT NULL,
    ngaysinh DATE NOT NULL,
    sdt NVARCHAR(20) NOT NULL
);


-- DIM MAYBAY
CREATE TABLE DIM_MAYBAY (
    mamb INT PRIMARY KEY NOT NULL,
    loaimaybay NVARCHAR(100) NOT NULL,
    nhasanxuat NVARCHAR(100) NOT NULL,
    succhua INT NOT NULL
);


-- DIM SANBAY
CREATE TABLE DIM_SANBAY (
    masb VARCHAR(10) PRIMARY KEY NOT NULL,
    tensb NVARCHAR(100) NOT NULL,
    thanhpho NVARCHAR(100) NOT NULL,
    quocgia NVARCHAR(100) NOT NULL
);


-- DIM TUYENBAY 
CREATE TABLE DIM_TUYENBAY (
    matb INT PRIMARY KEY NOT NULL,
    tentuyen NVARCHAR(100) NOT NULL,
    loaituyen NVARCHAR(50) NOT NULL
);


-- DIM KHUYENMAI
CREATE TABLE DIM_KHUYENMAI (
    makm INT PRIMARY KEY NOT NULL,
    tenkm NVARCHAR(100) NOT NULL,
    tylegiamgia FLOAT NOT NULL,
    sodiemcanthiet INT NOT NULL,
    ngaybatdau DATE NOT NULL,
    ngayketthuc DATE NOT NULL,
);


-- DIM CHUYENBAY
CREATE TABLE DIM_CHUYENBAY (
    macb INT PRIMARY KEY NOT NULL,
    mamb INT NOT NULL,
    matb INT NOT NULL,
    masbdi VARCHAR(10) NOT NULL,
    masbden VARCHAR(10) NOT NULL,
    FOREIGN KEY (mamb) REFERENCES DIM_MAYBAY(mamb),
    FOREIGN KEY (matb) REFERENCES DIM_TUYENBAY(matb),
    FOREIGN KEY (masbdi) REFERENCES DIM_SANBAY(masb),
    FOREIGN KEY (masbden) REFERENCES DIM_SANBAY(masb)
);


-- FACT DATCHO 
CREATE TABLE FACT_DATCHO ( 
    madatcho INT PRIMARY KEY NOT NULL,
    makh INT NOT NULL,
    macb INT NOT NULL,
    makenh INT NOT NULL,
    matg INT NOT NULL,
    soghe NVARCHAR(10) NOT NULL,
    giagoc FLOAT NOT NULL,
    giamgia FLOAT NOT NULL,
    thanhtien FLOAT NOT NULL,
    FOREIGN KEY (makh) REFERENCES DIM_KHACHHANG(makh),
    FOREIGN KEY (macb) REFERENCES DIM_CHUYENBAY(macb),
    FOREIGN KEY (matg) REFERENCES DIM_THOIGIAN(matg),
    FOREIGN KEY (makenh) REFERENCES DIM_KENHBANVE(makenh) 
);


-- FACT CSKH 
CREATE TABLE FACT_CSKH (
    mahotro INT PRIMARY KEY NOT NULL,
    makenh INT NOT NULL,
    makh INT NOT NULL,
    matg INT NOT NULL,
    macb INT NOT NULL,
    matacvu INT NOT NULL,
    manv INT NOT NULL,
    mucdouutien NVARCHAR(50) NOT NULL,
    FOREIGN KEY (makenh) REFERENCES DIM_KENHBANVE(makenh),
    FOREIGN KEY (makh) REFERENCES DIM_KHACHHANG(makh),
    FOREIGN KEY (matg) REFERENCES DIM_THOIGIAN(matg),
    FOREIGN KEY (macb) REFERENCES DIM_CHUYENBAY(macb),
    FOREIGN KEY (matacvu) REFERENCES DIM_TACVU(matacvu),
    FOREIGN KEY (manv) REFERENCES DIM_PHIHANHDOAN(manv)
);


-- FACT THONGTINCHUYENBAY
CREATE TABLE FACT_THONGTINCHUYENBAY (
    mathongtincb INT PRIMARY KEY NOT NULL,
    macb INT NOT NULL,
    macotruong INT NOT NULL,
    macopho INT NOT NULL,
    matiepvien INT NOT NULL,
    matg INT NOT NULL,
    soghetrong INT NOT NULL,
    sogiobayphd INT NOT NULL,
    FOREIGN KEY (macb) REFERENCES DIM_CHUYENBAY(macb),
    FOREIGN KEY (macotruong) REFERENCES DIM_PHIHANHDOAN(manv),
    FOREIGN KEY (macopho) REFERENCES DIM_PHIHANHDOAN(manv),
    FOREIGN KEY (matiepvien) REFERENCES DIM_PHIHANHDOAN(manv),
);


-- FACT TIEPTHI
CREATE TABLE FACT_TIEPTHI (
    matiepthi INT PRIMARY KEY NOT NULL,
    makh INT NOT NULL,
    makm INT NOT NULL,
    sodiemnhan INT NOT NULL,
    sodiemdoi INT NOT NULL,
    macb INT NOT NULL,
    matg INT NOT NULL,
    FOREIGN KEY (makh) REFERENCES DIM_KHACHHANG(makh),
    FOREIGN KEY (makm) REFERENCES DIM_KHUYENMAI(makm),
    FOREIGN KEY (macb) REFERENCES DIM_CHUYENBAY(macb),
    FOREIGN KEY (matg) REFERENCES DIM_THOIGIAN(matg)
);